# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: LSTM-50CL-ft
run_dir : Results/LSTM_50C/runs

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: data/local_basin_lists/LSTM_L.txt
validation_basin_file: data/local_basin_lists/LSTM_L.txt
test_basin_file: data/local_basin_lists/LSTM_L.txt

train_start_date: "01/01/1996"
train_end_date: "31/12/2013"
validation_start_date: "01/01/2014"
validation_end_date: "31/12/2015"
test_start_date: "01/01/2016"
test_end_date: "31/12/2020"

#### --------------------- Data configurations ----------------------------------------
dataset: generic
data_dir:  <ABSOLUTE_PATH_TO_LOCAL_DATA_DIRECTORY>  # e.g. /home/user/data

# --- Training configuration -----------------------------------------------------------------------
# early_stopping
early_stopping: True
minimum_epochs_before_early_stopping: 20
patience_early_stopping: 10

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate: 0.001

# Dropout applied to the output of the LSTM and internal structure
output_dropout: 0.4

dynamic_learning_rate: True
patience_dynamic_learning_rate: 5
factor_dynamic_learning_rate: 0.5

# Mini-batch size
batch_size: 128

# Number of training epochs
epochs: 100

# 
#lagged_features :
  #streamflow: 2

metrics:
  - NSE
  - KGE
  - RMSE
  - Pearson-r
  - FHV
  - FLV


finetune_modules:
- head
#- lstm

dynamic_inputs:
  - total_precipitation_sum
  - temperature_2m_mean
  - potential_evaporation_sum_ERA5_LAND

target_variables:
  - streamflow
clip_targets_to_zero:
  - streamflow

base_run_dir: Results/LSTM_50C/runs/LSTM_2603_134102

